import Head from "next/head";
import Image from "next/image";

import bg from "../../public/pictures/bg.webp";

import truck from "../../public/icons/truck.svg";
import house from "../../public/icons/house.svg";

import jonas from "../../public/pictures/jonas.webp";
import urte from "../../public/pictures/urte.webp";
import anatolijus from "../../public/pictures/anatolijus.webp";
import windmill from "../../public/icons/windmill.svg";
import tractor from "../../public/icons/tractor.svg";

import sutaupyk from "../../public/pictures/sutaupyk.webp";

export default function Home() {
  return (
    <>
      <Head>
        <title>Vegetables eshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-col">
        <Image
          className="mx-auto mt-20 h-[40vh] object-cover"
          src={bg}
          alt={bg}
          priority
          quality={100}
          placeholder="blur"
          blurDataURL="/pictures/bg.webp"
        />
        <Section1HomeDelivery />
        <Section2Stories />
        <Section3Discount />
      </main>
    </>
  );
}

const Section1HomeDelivery = () => {
  return (
    <section className="h-full text-myBlack">
      <div className="relative p-3">
        <Image src={truck} alt={truck} className="absolute top-16 right-3" />
        <Image src={house} alt={house} className="absolute bottom-4 left-3" />
        <h1 className="mr-24 text-left font-Cinzel text-3xl font-bold">
          Šviežios daržovės ir vaisiai
        </h1>
        <h1 className="ml-24 text-right font-Cinzel text-3xl font-bold">
          tiesiai į jūsų namus!
        </h1>
      </div>
      <p className="px-8 pt-3 pb-6 text-center font-Poppins text-2xl font-light">
        Pristatysime mūsų ekologiškas daržoves ir vaisius tiesiai jums į namus!
      </p>
    </section>
  );
};

const Section2Stories = () => {
  return (
    <section className="h-full bg-mySkin text-myBlack">
      <h1 className="pt-3 text-center font-Cinzel text-xl font-bold">
        Tik ekologiškos prekės
      </h1>
      <p className="px-8 pt-3 text-center font-Poppins text-2xl font-light">
        Visos mūsų parduodamos daržovės bei vaisiai yra{" "}
        <span className="font-medium">100% organiški</span> ir ekologišku
        tiesiai iš ūkininkų daržų bei sodų.
      </p>
      <p className="pt-6 text-center font-Poppins font-light underline">
        ūkininkų istorijos ir pasakojimai
      </p>

      <div className="mt-8 mb-6 space-y-3 px-3">
        <div className="flex items-center justify-between">
          <span className="flex flex-col items-center">
            <Image
              src={jonas}
              alt={jonas}
              quality={100}
              className="h-auto w-32 rounded-[35px]"
            />
            <h3 className="font-Poppins text-sm font-light">Jonas</h3>
          </span>
          <Image src={windmill} alt={windmill} quality={100} />
        </div>

        <span className="flex flex-col items-center">
          <Image
            src={urte}
            alt={urte}
            quality={100}
            className="h-auto w-32 rounded-[35px]"
          />
          <h3 className="font-Poppins text-sm font-light">Urtė</h3>
        </span>

        <div className="flex items-center justify-between">
          <Image src={tractor} alt={tractor} quality={100} />
          <span className="flex flex-col items-center">
            <Image
              src={anatolijus}
              alt={anatolijus}
              quality={100}
              className="h-auto w-32 rounded-[35px]"
            />
            <h3 className="font-Poppins text-sm font-light">Anatolijus</h3>
          </span>
        </div>
      </div>
    </section>
  );
};

const Section3Discount = () => {
  return (
    <section className="h-full text-myBlack">
      <h1 className="px-6 pt-3 text-center font-Cinzel text-xl font-bold">
        Pradėk 2023-uosius su vitaminu pliūpsniu.
      </h1>
      <span className="mx-14 mt-6 flex flex-col items-center">
        <button className="rounded bg-myGreen px-10 py-3 font-Cinzel text-xl font-bold text-myWhite drop-shadow-2xl">
          Kodas First20
        </button>
        <p className="mb-6 text-center font-Poppins text-[0.5rem] font-light">
          *Akcijos sąlygos gali keistis bet kuriuo metu ir mes neprivalome
          aiškintis.
        </p>
      </span>
      <Image
        src={sutaupyk}
        alt={sutaupyk}
        quality={100}
        placeholder="blur"
        priority
        className="object-cover"
        blurDataURL="/pictures/sutaupyk.webp"
      />
    </section>
  );
};
